server:
  port: 8089
spring:
  application:
    name: app
  aop:
    proxy-target-class: true
  datasource:
    name: writedb
#    url: jdbc:mysql://172.16.35.96:7001/test?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
#    username: route
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  readdb:
    name: readdb
#    url: jdbc:mysql://172.16.35.96:7002/test?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false
#    username: route
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: